X-Brand-Id:
X-Organ-Id:
X-City-Code:
city_name:
username:
password:
base-password:
authorization:
domain: https://
static-domain: https://
Referer: https://
Host:
estate_code:
estate_name:
admin_address:
buildings_id:
buildings_name:
unit_id:
unit_no:
surname:
- 梁
- 赵
- 钱
boy-name:
- 壮
- 昱杰
- 开虎
girl-name:
- 小玉
- 蓝
- 琬郡